name: Test

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - name: Lint basic
      env:
        RUSTFLAGS: -Dwarnings
      working-directory: ./examples/basic
      run: cargo clippy

    - name: Format basic
      working-directory: ./examples/basic
      run: cargo fmt -- --check

    - name: Lint scatter
      env:
        RUSTFLAGS: -Dwarnings
      working-directory: ./examples/scatter
      run: cargo clippy

    - name: Format scatter
      working-directory: ./examples/scatter
      run: cargo fmt -- --check

    - name: Lint bars
      env:
        RUSTFLAGS: -Dwarnings
      working-directory: ./examples/bars
      run: cargo clippy

    - name: Format bars
      working-directory: ./examples/bars
      run: cargo fmt -- --check

    - name: Lint lib
      env:
        RUSTFLAGS: -Dwarnings
      run: cargo clippy

    - name: Format lib
      run: cargo fmt -- --check

    - name: Test
      run: cargo test
